export const QUESTIONS = [
  {
    question_id: 1,
    text: "If you're given a complex jigsaw puzzle, how likely are you to finish it even if it takes several hours?",
    answers: ["Very unlikely", "Somewhat unlikely", "Likely", "Very likely"],
    weights: {
      "Data Analytics": [0, 1, 2, 3],
      Cybersecurity: [0, 1, 2, 2],
      "Web Development": [0, 1, 2, 1],
      "Product Design": [0, 1, 1, 1],
      "Digital Marketing": [0, 0, 1, 0],
    },
  },
  {
    question_id: 2,
    text: "You're in a room with six paint colors: black, yellow, red, blue, white, and green. Which combination would you use to design your ideal workspace?",
    answers: [
      "Bold colors that stand out",
      "Minimal neutral tones",
      "Bright and balanced hues",
      "Earthy and calm tones",
    ],
    weights: {
      "Data Analytics": [0, 3, 1, 2],
      Cybersecurity: [1, 3, 0, 1],
      "Web Development": [1, 2, 3, 1],
      "Product Design": [2, 1, 3, 2],
      "Digital Marketing": [3, 0, 2, 0],
    },
  },
  {
    question_id: 3,
    text: "When you meet new people, do you prefer to:",
    answers: ["Lead the conversation", "Listen and observe", "Ask thoughtful questions", "Keep it brief and move on"],
    weights: {
      "Data Analytics": [0, 2, 3, 1],
      Cybersecurity: [0, 3, 2, 1],
      "Web Development": [0, 1, 2, 1],
      "Product Design": [1, 1, 3, 0],
      "Digital Marketing": [3, 0, 2, 0],
    },
  },
  {
    question_id: 4,
    text: "How do you typically approach learning a new skill?",
    answers: [
      "Jump in and experiment",
      "Read documentation first",
      "Watch tutorials and follow along",
      "Ask someone experienced",
    ],
    weights: {
      "Data Analytics": [1, 3, 2, 1],
      Cybersecurity: [0, 3, 1, 2],
      "Web Development": [2, 2, 3, 1],
      "Product Design": [2, 1, 3, 1],
      "Digital Marketing": [2, 1, 2, 2],
    },
  },
  {
    question_id: 5,
    text: "When faced with a problem, your first instinct is to:",
    answers: ["Break it down into smaller parts", "Look for patterns", "Visualize the solution", "Discuss with others"],
    weights: {
      "Data Analytics": [3, 3, 1, 0],
      Cybersecurity: [3, 2, 0, 1],
      "Web Development": [2, 1, 3, 1],
      "Product Design": [1, 1, 3, 1],
      "Digital Marketing": [1, 1, 2, 3],
    },
  },
  {
    question_id: 6,
    text: "How comfortable are you with repetitive, detail-oriented tasks?",
    answers: ["Very uncomfortable", "Somewhat uncomfortable", "Comfortable", "Very comfortable"],
    weights: {
      "Data Analytics": [0, 1, 2, 3],
      Cybersecurity: [0, 1, 2, 3],
      "Web Development": [0, 1, 2, 2],
      "Product Design": [1, 2, 2, 1],
      "Digital Marketing": [1, 2, 1, 0],
    },
  },
  {
    question_id: 7,
    text: "What motivates you most in your work?",
    answers: [
      "Solving complex problems",
      "Protecting or securing something",
      "Creating something new",
      "Helping others succeed",
    ],
    weights: {
      "Data Analytics": [3, 0, 1, 1],
      Cybersecurity: [2, 3, 0, 1],
      "Web Development": [2, 0, 3, 1],
      "Product Design": [1, 0, 3, 2],
      "Digital Marketing": [1, 0, 2, 3],
    },
  },
  {
    question_id: 8,
    text: "How do you feel about working with numbers and statistics?",
    answers: ["Dislike it", "Neutral", "Enjoy it", "Love it"],
    weights: {
      "Data Analytics": [0, 1, 2, 3],
      Cybersecurity: [0, 1, 2, 2],
      "Web Development": [0, 2, 1, 0],
      "Product Design": [0, 2, 1, 0],
      "Digital Marketing": [0, 1, 2, 1],
    },
  },
  {
    question_id: 9,
    text: "When something goes wrong, you typically:",
    answers: [
      "Get frustrated quickly",
      "Stay calm and investigate",
      "Look for who's responsible",
      "Try to fix it immediately",
    ],
    weights: {
      "Data Analytics": [0, 3, 1, 1],
      Cybersecurity: [0, 3, 2, 1],
      "Web Development": [1, 2, 0, 3],
      "Product Design": [1, 2, 0, 2],
      "Digital Marketing": [1, 1, 2, 1],
    },
  },
  {
    question_id: 10,
    text: "How important is it for you to understand the 'why' behind things?",
    answers: ["Not important", "Somewhat important", "Important", "Very important"],
    weights: {
      "Data Analytics": [0, 1, 2, 3],
      Cybersecurity: [0, 1, 2, 3],
      "Web Development": [0, 1, 2, 2],
      "Product Design": [1, 1, 2, 2],
      "Digital Marketing": [1, 2, 2, 1],
    },
  },
  {
    question_id: 11,
    text: "Your ideal work environment is:",
    answers: ["Quiet and focused", "Collaborative and social", "Flexible and independent", "Structured and organized"],
    weights: {
      "Data Analytics": [2, 0, 1, 3],
      Cybersecurity: [2, 0, 1, 3],
      "Web Development": [1, 1, 3, 1],
      "Product Design": [1, 2, 2, 1],
      "Digital Marketing": [0, 3, 1, 1],
    },
  },
  {
    question_id: 12,
    text: "How do you handle feedback on your work?",
    answers: ["Take it personally", "Listen but stay confident", "Use it to improve", "Seek it out actively"],
    weights: {
      "Data Analytics": [0, 1, 3, 2],
      Cybersecurity: [0, 1, 3, 2],
      "Web Development": [0, 1, 3, 2],
      "Product Design": [0, 1, 3, 3],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 13,
    text: "When learning about a new technology, you prefer to:",
    answers: ["Understand the theory first", "See practical examples", "Build something with it", "Read case studies"],
    weights: {
      "Data Analytics": [3, 1, 1, 2],
      Cybersecurity: [3, 1, 1, 2],
      "Web Development": [1, 2, 3, 1],
      "Product Design": [1, 2, 3, 1],
      "Digital Marketing": [1, 2, 1, 3],
    },
  },
  {
    question_id: 14,
    text: "How do you feel about presenting your ideas to a large group?",
    answers: ["Very anxious", "Somewhat nervous", "Comfortable", "Excited"],
    weights: {
      "Data Analytics": [2, 1, 0, 0],
      Cybersecurity: [2, 1, 0, 0],
      "Web Development": [1, 2, 1, 0],
      "Product Design": [1, 1, 2, 1],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 15,
    text: "What's your relationship with deadlines?",
    answers: ["I work best under pressure", "I prefer planning ahead", "I need some structure", "I'm flexible"],
    weights: {
      "Data Analytics": [0, 3, 2, 0],
      Cybersecurity: [0, 3, 2, 0],
      "Web Development": [1, 2, 2, 1],
      "Product Design": [1, 2, 2, 1],
      "Digital Marketing": [2, 1, 1, 1],
    },
  },
  {
    question_id: 16,
    text: "How do you typically spend your free time?",
    answers: ["Reading or learning", "Creating or building", "Socializing", "Exploring new things"],
    weights: {
      "Data Analytics": [3, 1, 0, 1],
      Cybersecurity: [3, 1, 0, 1],
      "Web Development": [1, 3, 0, 2],
      "Product Design": [1, 3, 1, 2],
      "Digital Marketing": [1, 1, 3, 2],
    },
  },
  {
    question_id: 17,
    text: "When working on a team project, you usually:",
    answers: ["Take charge", "Support others", "Work independently", "Coordinate efforts"],
    weights: {
      "Data Analytics": [0, 1, 2, 2],
      Cybersecurity: [0, 1, 2, 2],
      "Web Development": [1, 1, 2, 1],
      "Product Design": [1, 2, 1, 2],
      "Digital Marketing": [2, 1, 0, 2],
    },
  },
  {
    question_id: 18,
    text: "How do you feel about ambiguity and uncertainty?",
    answers: ["Very uncomfortable", "Somewhat uncomfortable", "Comfortable", "Thrive in it"],
    weights: {
      "Data Analytics": [3, 2, 1, 0],
      Cybersecurity: [3, 2, 1, 0],
      "Web Development": [1, 1, 2, 2],
      "Product Design": [1, 1, 2, 3],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 19,
    text: "What type of problems excite you most?",
    answers: ["Logical puzzles", "Real-world challenges", "Creative problems", "People-related issues"],
    weights: {
      "Data Analytics": [3, 2, 0, 0],
      Cybersecurity: [2, 3, 0, 0],
      "Web Development": [1, 2, 3, 0],
      "Product Design": [0, 1, 3, 1],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 20,
    text: "How important is it for you to see the impact of your work?",
    answers: ["Not important", "Somewhat important", "Important", "Very important"],
    weights: {
      "Data Analytics": [1, 1, 2, 2],
      Cybersecurity: [0, 1, 2, 3],
      "Web Development": [0, 1, 2, 3],
      "Product Design": [0, 1, 2, 3],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 21,
    text: "When faced with conflicting information, you:",
    answers: ["Trust your gut", "Seek more data", "Ask for expert opinion", "Take time to decide"],
    weights: {
      "Data Analytics": [0, 3, 1, 2],
      Cybersecurity: [0, 3, 2, 1],
      "Web Development": [1, 2, 1, 2],
      "Product Design": [1, 1, 2, 2],
      "Digital Marketing": [1, 1, 2, 2],
    },
  },
  {
    question_id: 22,
    text: "How do you feel about following established rules and procedures?",
    answers: ["Prefer to break them", "Follow when necessary", "Appreciate structure", "Strictly adhere"],
    weights: {
      "Data Analytics": [0, 1, 2, 3],
      Cybersecurity: [0, 1, 2, 3],
      "Web Development": [2, 2, 1, 0],
      "Product Design": [2, 2, 1, 0],
      "Digital Marketing": [2, 2, 1, 0],
    },
  },
  {
    question_id: 23,
    text: "What's your approach to staying updated with industry trends?",
    answers: ["Rarely follow trends", "Occasionally check", "Regularly stay informed", "Obsessively track everything"],
    weights: {
      "Data Analytics": [0, 1, 2, 2],
      Cybersecurity: [0, 1, 3, 3],
      "Web Development": [0, 1, 2, 2],
      "Product Design": [0, 1, 2, 2],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 24,
    text: "How do you typically communicate complex ideas?",
    answers: ["Through visuals", "With detailed explanations", "Using analogies", "Through data"],
    weights: {
      "Data Analytics": [0, 2, 1, 3],
      Cybersecurity: [0, 2, 1, 2],
      "Web Development": [2, 1, 1, 1],
      "Product Design": [3, 1, 2, 0],
      "Digital Marketing": [2, 1, 3, 1],
    },
  },
  {
    question_id: 25,
    text: "When a project fails, you typically:",
    answers: ["Blame external factors", "Analyze what went wrong", "Move on quickly", "Feel discouraged"],
    weights: {
      "Data Analytics": [0, 3, 1, 0],
      Cybersecurity: [0, 3, 1, 0],
      "Web Development": [0, 2, 2, 1],
      "Product Design": [0, 2, 1, 2],
      "Digital Marketing": [0, 2, 2, 1],
    },
  },
  {
    question_id: 26,
    text: "How comfortable are you with continuous learning and change?",
    answers: ["Very uncomfortable", "Somewhat uncomfortable", "Comfortable", "Thrive on it"],
    weights: {
      "Data Analytics": [0, 1, 2, 3],
      Cybersecurity: [0, 1, 2, 3],
      "Web Development": [0, 1, 2, 3],
      "Product Design": [0, 1, 2, 3],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 27,
    text: "Your ideal project would involve:",
    answers: [
      "Analyzing large datasets",
      "Securing systems",
      "Building user interfaces",
      "Designing experiences",
      "Reaching audiences",
    ],
    weights: {
      "Data Analytics": [3, 0, 0, 0, 0],
      Cybersecurity: [0, 3, 0, 0, 0],
      "Web Development": [0, 0, 3, 0, 0],
      "Product Design": [0, 0, 1, 3, 0],
      "Digital Marketing": [0, 0, 0, 1, 3],
    },
  },
  {
    question_id: 28,
    text: "How do you handle stress and pressure?",
    answers: ["Get overwhelmed", "Stay calm and focused", "Channel it productively", "Seek support"],
    weights: {
      "Data Analytics": [0, 3, 1, 1],
      Cybersecurity: [0, 3, 2, 1],
      "Web Development": [0, 2, 2, 1],
      "Product Design": [0, 1, 2, 2],
      "Digital Marketing": [0, 1, 2, 2],
    },
  },
  {
    question_id: 29,
    text: "What role do you prefer in group settings?",
    answers: ["Leader", "Specialist", "Collaborator", "Observer"],
    weights: {
      "Data Analytics": [0, 3, 1, 1],
      Cybersecurity: [0, 3, 1, 1],
      "Web Development": [0, 2, 2, 1],
      "Product Design": [1, 1, 3, 0],
      "Digital Marketing": [2, 1, 2, 0],
    },
  },
  {
    question_id: 30,
    text: "How do you feel about working with code or technical systems?",
    answers: ["Intimidated", "Neutral", "Comfortable", "Passionate"],
    weights: {
      "Data Analytics": [0, 1, 2, 3],
      Cybersecurity: [0, 1, 2, 3],
      "Web Development": [0, 1, 2, 3],
      "Product Design": [0, 2, 2, 1],
      "Digital Marketing": [0, 2, 1, 0],
    },
  },
  {
    question_id: 31,
    text: "When given a choice, you prefer tasks that are:",
    answers: ["Highly structured", "Moderately flexible", "Very creative", "Collaborative"],
    weights: {
      "Data Analytics": [3, 1, 0, 0],
      Cybersecurity: [3, 1, 0, 0],
      "Web Development": [1, 2, 2, 1],
      "Product Design": [0, 1, 3, 1],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 32,
    text: "How do you approach risk?",
    answers: ["Avoid it at all costs", "Minimize it carefully", "Accept calculated risks", "Embrace uncertainty"],
    weights: {
      "Data Analytics": [2, 2, 1, 0],
      Cybersecurity: [2, 3, 1, 0],
      "Web Development": [0, 1, 3, 1],
      "Product Design": [0, 1, 2, 2],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 33,
    text: "What energizes you most at work?",
    answers: ["Solving problems", "Helping others", "Creating something new", "Achieving goals"],
    weights: {
      "Data Analytics": [3, 0, 1, 2],
      Cybersecurity: [2, 1, 0, 2],
      "Web Development": [2, 0, 3, 1],
      "Product Design": [1, 1, 3, 1],
      "Digital Marketing": [1, 2, 2, 3],
    },
  },
  {
    question_id: 34,
    text: "How do you feel about documentation and record-keeping?",
    answers: ["Tedious", "Necessary", "Important", "Essential"],
    weights: {
      "Data Analytics": [0, 1, 2, 3],
      Cybersecurity: [0, 1, 2, 3],
      "Web Development": [0, 2, 2, 1],
      "Product Design": [0, 2, 2, 1],
      "Digital Marketing": [0, 2, 1, 0],
    },
  },
  {
    question_id: 35,
    text: "Your communication style is typically:",
    answers: ["Direct and concise", "Detailed and thorough", "Engaging and persuasive", "Collaborative and open"],
    weights: {
      "Data Analytics": [1, 3, 0, 1],
      Cybersecurity: [1, 3, 0, 1],
      "Web Development": [1, 2, 0, 2],
      "Product Design": [0, 1, 2, 2],
      "Digital Marketing": [0, 1, 3, 1],
    },
  },
  {
    question_id: 36,
    text: "How do you feel about user feedback and testing?",
    answers: ["Unnecessary", "Somewhat useful", "Very important", "Critical"],
    weights: {
      "Data Analytics": [0, 1, 2, 2],
      Cybersecurity: [0, 1, 2, 2],
      "Web Development": [0, 1, 2, 3],
      "Product Design": [0, 1, 2, 3],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 37,
    text: "When learning something new, you prefer:",
    answers: ["Self-paced learning", "Structured courses", "Hands-on projects", "Mentorship"],
    weights: {
      "Data Analytics": [2, 2, 1, 1],
      Cybersecurity: [2, 2, 1, 1],
      "Web Development": [1, 1, 3, 1],
      "Product Design": [1, 1, 3, 1],
      "Digital Marketing": [1, 1, 2, 2],
    },
  },
  {
    question_id: 38,
    text: "How important is work-life balance to you?",
    answers: ["Not important", "Somewhat important", "Important", "Very important"],
    weights: {
      "Data Analytics": [1, 1, 2, 2],
      Cybersecurity: [0, 1, 2, 3],
      "Web Development": [1, 1, 2, 2],
      "Product Design": [1, 1, 2, 2],
      "Digital Marketing": [1, 1, 2, 2],
    },
  },
  {
    question_id: 39,
    text: "Your natural strength is:",
    answers: ["Logical thinking", "Attention to detail", "Creative vision", "People skills"],
    weights: {
      "Data Analytics": [3, 2, 0, 0],
      Cybersecurity: [2, 3, 0, 0],
      "Web Development": [2, 1, 3, 0],
      "Product Design": [1, 1, 3, 1],
      "Digital Marketing": [1, 0, 2, 3],
    },
  },
  {
    question_id: 40,
    text: "How do you feel about mentoring or teaching others?",
    answers: ["Uncomfortable", "Willing if asked", "Enjoy it", "Love it"],
    weights: {
      "Data Analytics": [1, 1, 2, 1],
      Cybersecurity: [1, 1, 2, 1],
      "Web Development": [1, 1, 2, 1],
      "Product Design": [1, 1, 2, 2],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 41,
    text: "When faced with a new tool or software, you:",
    answers: ["Avoid it", "Use it reluctantly", "Learn it gradually", "Dive in immediately"],
    weights: {
      "Data Analytics": [0, 1, 2, 2],
      Cybersecurity: [0, 1, 2, 2],
      "Web Development": [0, 1, 2, 3],
      "Product Design": [0, 1, 2, 2],
      "Digital Marketing": [0, 1, 2, 2],
    },
  },
  {
    question_id: 42,
    text: "Your ideal career progression involves:",
    answers: ["Becoming an expert", "Leading a team", "Starting something new", "Helping others grow"],
    weights: {
      "Data Analytics": [3, 1, 0, 0],
      Cybersecurity: [3, 1, 0, 0],
      "Web Development": [2, 1, 2, 0],
      "Product Design": [1, 1, 2, 1],
      "Digital Marketing": [1, 2, 2, 2],
    },
  },
  {
    question_id: 43,
    text: "How do you handle criticism?",
    answers: ["Take it personally", "Listen objectively", "Use it constructively", "Seek it out"],
    weights: {
      "Data Analytics": [0, 2, 3, 1],
      Cybersecurity: [0, 2, 3, 1],
      "Web Development": [0, 1, 3, 1],
      "Product Design": [0, 1, 3, 2],
      "Digital Marketing": [0, 1, 2, 2],
    },
  },
  {
    question_id: 44,
    text: "What's your relationship with innovation?",
    answers: ["Prefer proven methods", "Open to new ideas", "Actively seek innovation", "Drive innovation"],
    weights: {
      "Data Analytics": [1, 2, 1, 0],
      Cybersecurity: [1, 2, 1, 0],
      "Web Development": [0, 1, 3, 2],
      "Product Design": [0, 1, 3, 3],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 45,
    text: "How do you feel about working with diverse teams?",
    answers: ["Prefer homogeneous teams", "Neutral", "Enjoy diversity", "Thrive with diversity"],
    weights: {
      "Data Analytics": [1, 2, 1, 0],
      Cybersecurity: [1, 2, 1, 0],
      "Web Development": [0, 1, 2, 2],
      "Product Design": [0, 1, 2, 3],
      "Digital Marketing": [0, 1, 2, 3],
    },
  },
  {
    question_id: 46,
    text: "Your approach to problem-solving is:",
    answers: ["Intuitive", "Methodical", "Creative", "Collaborative"],
    weights: {
      "Data Analytics": [0, 3, 1, 1],
      Cybersecurity: [0, 3, 1, 1],
      "Web Development": [1, 2, 2, 1],
      "Product Design": [1, 1, 3, 1],
      "Digital Marketing": [1, 1, 2, 2],
    },
  },
  {
    question_id: 47,
    text: "How important is job security to you?",
    answers: ["Very important", "Somewhat important", "Not very important", "Not important at all"],
    weights: {
      "Data Analytics": [2, 2, 1, 0],
      Cybersecurity: [2, 2, 1, 0],
      "Web Development": [1, 1, 2, 1],
      "Product Design": [1, 1, 2, 1],
      "Digital Marketing": [1, 1, 2, 1],
    },
  },
  {
    question_id: 48,
    text: "When working on a project, you focus most on:",
    answers: ["Accuracy", "Efficiency", "User experience", "Market impact"],
    weights: {
      "Data Analytics": [3, 2, 0, 0],
      Cybersecurity: [3, 2, 0, 0],
      "Web Development": [1, 1, 3, 1],
      "Product Design": [1, 1, 3, 1],
      "Digital Marketing": [0, 1, 1, 3],
    },
  },
  {
    question_id: 49,
    text: "How do you feel about working independently?",
    answers: ["Prefer collaboration", "Comfortable either way", "Prefer independence", "Thrive alone"],
    weights: {
      "Data Analytics": [0, 1, 2, 2],
      Cybersecurity: [0, 1, 2, 2],
      "Web Development": [0, 1, 2, 2],
      "Product Design": [0, 1, 2, 1],
      "Digital Marketing": [0, 1, 1, 0],
    },
  },
  {
    question_id: 50,
    text: "Your biggest professional goal is to:",
    answers: ["Become an expert", "Lead others", "Create impact", "Help people"],
    weights: {
      "Data Analytics": [3, 1, 1, 0],
      Cybersecurity: [3, 1, 1, 0],
      "Web Development": [2, 1, 2, 0],
      "Product Design": [1, 1, 3, 1],
      "Digital Marketing": [1, 2, 2, 2],
    },
  },
]
